dist: focal
language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/pecl_cache

env:
  global:
    - COMPOSER_ARGS=install
    - OPENSWOOLE_VERSION=4.10.0

matrix:
  include:
    - php: "7.4"
    - php: "8.0"
      env:
        - PHP_CS_FIXER_IGNORE_ENV=1
    - php: "8.0"
      env:
        - OPENSWOOLE_LATEST=1
        - COMPOSER_ARGS='update'
        - NO_ANALYSE=1
    - php: "8.1"
      env:
        - PHP_CS_FIXER_IGNORE_ENV=1
    - php: "8.1"
      env:
        - OPENSWOOLE_LATEST=1
        - COMPOSER_ARGS='update'
        - NO_ANALYSE=1
  fast_finish: true
  allow_failures:
    - php: "8.0"
      env:
        - OPENSWOOLE_LATEST=1
        - COMPOSER_ARGS='update'
        - NO_ANALYSE=1
    - php: "8.1"
      env:
        - OPENSWOOLE_LATEST=1
        - COMPOSER_ARGS='update'
        - NO_ANALYSE=1

before_script:
  - phpenv config-rm xdebug.ini

before_install:
  - export PATH="$PATH:$HOME/.config/composer/vendor/bin"
  - composer global require phwoolcon/ci-pecl-cacher
  - pecl update-channels
  - ci-pecl-install inotify
  - >-
      if [[ "$OPENSWOOLE_LATEST" = "1" ]]; then
        ci-pecl-install openswoole;
      else
        ci-pecl-install openswoole-$OPENSWOOLE_VERSION openswoole skip-update;
      fi
  - php -r "echo swoole_version().PHP_EOL;"

install:
  - export COMPOSER_ARGS="$COMPOSER_ARGS --prefer-dist --no-progress --no-suggest --ansi"
  - echo "composer $COMPOSER_ARGS"
  - composer $COMPOSER_ARGS

script:
  - >-
      if [[ "NO_ANALYSE" != "1" ]]; then
        composer analyse
      fi
  - composer unit-tests
  - composer feature-tests
